#!/usr/bin/env bash
cd "$(git rev-parse --show-toplevel)"
hash=$(git rev-parse --short HEAD)
subject=$(git log -1 --pretty=%s)
ts=$(date +"%Y-%m-%dT%H:%M:%S%z" | sed 's/\([0-9][0-9]\)$/:\1/')
{
  echo "${ts} commit ${hash} \"${subject}\""
  echo "  -> Claude_Brain/99_Meta/log.mdにこのコミットを反映したか確認せよ"
  echo "  -> 返信の最後にRule13の表(状態/ファイル名/保存先)を出したか確認せよ"
} >> .vault-log-pending
